---
title: "enterobacteriaceae-tree"
output: html_document
---

##Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("GenomicBreaks") |> suppressPackageStartupMessages()
library("ggplot2")
library("pheatmap")
library("plotly")
library("dplyr")
library("dendextend")
library("BiocManager")
library("ggtree")
library("phytools")
library("ape")
library("rrapply")
library("tidytree")
library("viridis")
library("ggnewscale")
library("readr")
```


##H. salinarum Data
```{r}
params <- list()
params$resultsDir <- '/flash/LuscombeU/noa/bacteria/results/genomicbreaks'
yamlFiles <- list.files(params$resultsDir, pattern = "*.yaml", full.names = TRUE)
names(yamlFiles) <- yamlFiles |> basename() |> sub(pat = ".yaml", rep="")

getStats <- function(file) {
  y <- yaml::read_yaml(file) |> yaml::yaml.load()
  unlist(y)
}

df <- do.call(rbind, lapply(yamlFiles, getStats)) |> as.data.frame()
df <- df[,colSums(df, na.rm = TRUE) !=0]
df$species1 <- strsplit(rownames(df), "___") |> lapply(\(.) .[1]) |> unlist()
df$species2 <- strsplit(rownames(df), "___") |> lapply(\(.) .[2]) |> unlist()
df <- df[df$species1 != df$species2,]
df$index_avg_strandRand   <- ( df$index_strandRand_target + df$index_strandRand_query ) / 2
df$percent_identity_global   <- df$matches_number_Total    / df$aligned_length_Total * 100

makeMatrix <- function(df, column, defaultDiagonal = 100, defaultValue = NA) {
  species <- unique(df$species2)
  m <- matrix(defaultValue, nrow=length(species), ncol=length(species))
  colnames(m) <- rownames(m) <- species
  for (i in 1:length(species)) {
    m[i,i] <- defaultDiagonal
  }
  for (i in 1:nrow(df)) {
    s1 <- df[i, "species1"]
    s2 <- df[i, "species2"]
    if(s1 %in% species)
      m[s1, s2] <- df[i, column]
  }
  m
}
```


##H. salinarum Percent Identity & Strand Randomisation Tree
```{r}
m <- makeMatrix(df, "percent_identity_global", 100, 50)
hclust <- hclust(dist(m), method = "complete")
dend <- as.dendrogram(hclust)
m1 <- makeMatrix(df, "index_avg_strandRand", 100, 50)

extractStrandRandIDs <- function(node, tibble, matrix, fun = mean) {
  children <- child(tibble, node)
  stopifnot(nrow(children) == 2)
  left_side_node  <- children[1, "node", drop = TRUE]
  right_side_node <- children[2, "node", drop = TRUE]
  tipLabels <- function(node, tibble) {
    tipLabel <- tibble[node,"label", drop = TRUE]
    if(!is.na(tipLabel)) return(tipLabel)
    offspring(tibble, node)$label |> Filter(complete.cases, x=_)
  }
  left_side_species  <- tipLabels(left_side_node,  tibble)
  right_side_species <- tipLabels(right_side_node, tibble)
  comparison <- matrix[left_side_species, right_side_species, drop=F]
  strandRand <- fun(comparison)
  strandRand
}

extractPercentID <- function(node, tibble, matrix, fun = mean) {
  children <- child(tibble, node)
  stopifnot(nrow(children) == 2)
  left_side_node  <- children[1, "node", drop = TRUE]
  right_side_node <- children[2, "node", drop = TRUE]
  tipLabels <- function(node, tibble) {
    tipLabel <- tibble[node,"label", drop = TRUE]
    if(!is.na(tipLabel)) return(tipLabel)
    offspring(tibble, node)$label |> Filter(complete.cases, x=_)
  }
  left_side_species  <- tipLabels(left_side_node,  tibble)
  right_side_species <- tipLabels(right_side_node, tibble)
  comparison <- matrix[left_side_species, right_side_species, drop=F]
  percentID <- fun(comparison)
  percentID
}

as_tibble(as.phylo(dend)) -> td
sRIs <- unique(td$parent) |> sort() |> purrr::set_names() |> sapply(extractStrandRandIDs, td, m1)
pIDs <- unique(td$parent) |> sort() |> purrr::set_names() |> sapply(extractPercentID, td, m)
td$strandRand <- NA
td$percentID <- NA
td[names(sRIs), "strandRand"] <- unname(sRIs)
td[names(pIDs), "percentID"] <- unname(pIDs)

##Find Node Numbers
ggtree(as.treedata(td), branch.length='none') + 
  geom_tiplab(as_ylab=TRUE) + 
  geom_text(aes(label=node))

##No Branch Length
td2 <- groupClade(td, c(108, 111, 122, 124, 127, 132, 139, 140))

nbl_ent <- ggtree(as.treedata(td2), branch.length = "none") +
  ggtitle("Enterobacteria: Percent Identity & Strand Randomisation Index (no branch length)") +
  geom_tippoint(aes(color=group), show.legend = FALSE) +
  scale_color_manual(values=c("#328FB1", "#ACDBC9", "#DBECC0", "#FDD285", "#F7A7A6", "#F4BA94", "#DFACF6", "#8D9DF5")) +
  new_scale_colour() +
  geom_tiplab(as_ylab=TRUE) +
  geom_label(aes(label=round(strandRand, digit = 2), color = strandRand), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = 0.5) +
  scale_color_viridis(name = "Strand Randomisation Index", limits = c(0,1)) +
  new_scale_colour() +
  geom_label(aes(label=round(percentID, digit = 1), color = percentID), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = -0.5) +
  scale_color_viridis(option="magma", name = "Percent Identity", limits = c(51,100))
nbl_ent

nbl_ent2 <- groupClade(nbl_ent, c(112, 115))

nbl_ent_collapse <- nbl_ent %>% ggtree::collapse(node=112) +
  geom_point2(aes(subset=(node==112)), shape=23, size = 3, fill = "red")

nbl_ent_collapse2 <- nbl_ent_collapse %>% ggtree::collapse(node=115) +
  geom_point2(aes(subset=(node==115)), shape=21, size = 3, fill = "blue")

nbl_ent_collapse2

viewClade(nbl_ent, MRCA(nbl_ent, "Blochmannia_endosymbiont_of_Camponotus_nipponensis", "Kosakonia_sacchari"))






##With Branch Length
bl_ent <- ggtree(as.treedata(td2)) +
  ggtitle("Enterobacteria: Percent Identity & Strand Randomisation Index (no branch length)") +
  geom_tippoint(aes(color=group), show.legend = FALSE) +
  scale_color_manual(values=c("black", "#ACDBC9", "#DBECC0", "#FDD285", "#F7A7A6", "#F4BA94", "#DFACF6", "#8D9DF5")) +
  new_scale_colour() +
  geom_tiplab(as_ylab=TRUE) +
  geom_label(aes(label=round(strandRand, digit = 2), color = strandRand), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = 0.5) +
  scale_color_viridis(name = "Strand Randomisation Index") +
  new_scale_colour() +
  geom_label(aes(label=round(percentID, digit = 1), color = percentID), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = -0.5) +
  scale_color_viridis(option="magma", name = "Percent Identity")
bl_ent

viewClade(bl_ent, MRCA(bl_ent, "Halobacterium_salinarum_UC4241", "Halobacterium_salinarum_KBTZ01"))

```
