---
title: "fungi-tree"
output: html_document
date: "2023-07-11"
---


##Libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("GenomicBreaks") |> suppressPackageStartupMessages()
library("ggplot2")
library("pheatmap")
library("plotly")
library("dplyr")
library("dendextend")
library("BiocManager")
library("ggtree")
library("phytools")
library("ape")
library("rrapply")
library("tidytree")
library("viridis")
library("ggnewscale")
library("readr")
library("ggrepel")
library("RColorBrewer")
library("scales")
```


##Fungi Data
```{r}
params <- list()
params$resultsDir <- '/flash/LuscombeU/noa/fungi/results/genomicbreaks'
yamlFiles <- list.files(params$resultsDir, pattern = "*.yaml", full.names = TRUE)
names(yamlFiles) <- yamlFiles |> basename() |> sub(pat = ".yaml", rep="")

getStats <- function(file) {
  y <- yaml::read_yaml(file) |> yaml::yaml.load()
  unlist(y)
}

df <- do.call(rbind, lapply(yamlFiles, getStats)) |> as.data.frame()
df <- df[,colSums(df, na.rm = TRUE) !=0]
df$species1 <- strsplit(rownames(df), "___") |> lapply(\(.) .[1]) |> unlist()
df$species2 <- strsplit(rownames(df), "___") |> lapply(\(.) .[2]) |> unlist()
df <- df[df$species1 != df$species2,]
df$index_avg_strandRand   <- ( df$index_strandRand_target + df$index_strandRand_query ) / 2
df$percent_identity_global <- df$aligned_matches_Total / df$aligned_length_Total * 100

makeMatrix <- function(df, column, defaultDiagonal = 100, defaultValue = NA) {
  species <- unique(df$species2)
  m <- matrix(defaultValue, nrow=length(species), ncol=length(species))
  colnames(m) <- rownames(m) <- species
  for (i in 1:length(species)) {
    m[i,i] <- defaultDiagonal
  }
  for (i in 1:nrow(df)) {
    s1 <- df[i, "species1"]
    s2 <- df[i, "species2"]
    if(s1 %in% species)
      m[s1, s2] <- df[i, column]
  }
  m
}
```


##Tree Data
```{r}
m <- makeMatrix(df, "percent_identity_global", 100, 50)
hclust <- hclust(dist(m), method = "complete")
dend <- as.dendrogram(hclust)
m1 <- makeMatrix(df, "index_avg_strandRand", 100, 50)

extractStrandRandIDs <- function(node, tibble, matrix, fun = mean) {
  children <- child(tibble, node)
  stopifnot(nrow(children) == 2)
  left_side_node  <- children[1, "node", drop = TRUE]
  right_side_node <- children[2, "node", drop = TRUE]
  tipLabels <- function(node, tibble) {
    tipLabel <- tibble[node,"label", drop = TRUE]
    if(!is.na(tipLabel)) return(tipLabel)
    offspring(tibble, node)$label |> Filter(complete.cases, x=_)
  }
  left_side_species  <- tipLabels(left_side_node,  tibble)
  right_side_species <- tipLabels(right_side_node, tibble)
  comparison <- matrix[left_side_species, right_side_species, drop=F]
  strandRand <- fun(comparison)
  strandRand
}

extractPercentID <- function(node, tibble, matrix, fun = mean) {
  children <- child(tibble, node)
  stopifnot(nrow(children) == 2)
  left_side_node  <- children[1, "node", drop = TRUE]
  right_side_node <- children[2, "node", drop = TRUE]
  tipLabels <- function(node, tibble) {
    tipLabel <- tibble[node,"label", drop = TRUE]
    if(!is.na(tipLabel)) return(tipLabel)
    offspring(tibble, node)$label |> Filter(complete.cases, x=_)
  }
  left_side_species  <- tipLabels(left_side_node,  tibble)
  right_side_species <- tipLabels(right_side_node, tibble)
  comparison <- matrix[left_side_species, right_side_species, drop=F]
  percentID <- fun(comparison)
  percentID
}

as_tibble(as.phylo(dend)) -> td
sRIs <- unique(td$parent) |> sort() |> purrr::set_names() |> sapply(extractStrandRandIDs, td, m1)
pIDs <- unique(td$parent) |> sort() |> purrr::set_names() |> sapply(extractPercentID, td, m)
td$strandRand <- NA
td$percentID <- NA
td[names(sRIs), "strandRand"] <- unname(sRIs)
td[names(pIDs), "percentID"] <- unname(pIDs)
```


##Trees: Fungi
```{r}
##Find Node Numbers
ggtree(as.treedata(td), branch.length='none') + 
  geom_tiplab(as_ylab=TRUE) + 
  geom_text(aes(label=node))

##No Branch Length
td2 <- groupClade(td, c(86,87,93,92,78,84,96,37,64,109,102,90,94,5,101,74,76,82,100,111,114,115))

nbl_fun <- ggtree(as.treedata(td2), branch.length = "none") +
  ggtitle("Fungi: Percent Identity & Strand Randomisation Index (no branch length)") +
  geom_tippoint(aes(color=group), show.legend = FALSE) +
  scale_color_manual(values=c("#f45151", "black", "#e55c3c", "black", "#d36629", "#d36629", "#c06e1a", "black", "black", "black", "black", "#98790d", "#857c15", "black", "#727e21", "#5f7e2d", "#4d7d3a", "#3c7c47", "black", "black", "#2b7a53", "#1b775d", "#0c7466", "#0a706c")) +
  new_scale_colour() +
  geom_tiplab(as_ylab=TRUE) +
  geom_label(aes(label=round(percentID, digit = 1), color = percentID), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = -0.5) +
  scale_color_gradientn(colours = c("#440154FF", "#482173FF", "#433E85FF", "#38598CFF", "#2D708EFF", "#25858EFF", "#1E9B8AFF", "#2BB07FFF", "#51C56AFF", "#85D54AFF", "#C2DF23FF"), name = "Percent Identity") +
  new_scale_colour() +
  geom_label2(aes(label=round(strandRand, digit = 2), color = strandRand, subset = !is.na(as.numeric(strandRand)) & as.numeric(strandRand) < 1.01), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = 0.5) +
  scale_color_gradientn(colours = c("#0D0887FF", "#3E049CFF", "#6300A7FF", "#8707A6FF", "#A62098FF", "#C03A83FF", "#D5546EFF", "#F58C46FF"), name = "Strand Randomisation Index")
nbl_fun




nbl_fun <- ggtree(as.treedata(td2), branch.length = "none") +
  ggtitle("Fungi: Percent Identity & Strand Randomisation Index (no branch length)") +
  geom_tippoint(aes(color=group), show.legend = FALSE) +
  scale_color_manual(values=c("#f45151", "black", "#e55c3c", "black", "#d36629", "#d36629", "#c06e1a", "black", "black", "black", "black", "#98790d", "#857c15", "black", "#727e21", "#5f7e2d", "#4d7d3a", "#3c7c47", "black", "black", "#2b7a53", "#1b775d", "#0c7466", "#0a706c")) +
  new_scale_colour() +
  geom_tiplab(as_ylab=TRUE) +
  geom_label2(aes(label=round(strandRand, digit = 2), color = strandRand, subset = !is.na(as.numeric(strandRand)) & as.numeric(strandRand) < 1.01), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = 0.5) +
  scale_color_gradientn(colours = c("#0D0887FF", "#3E049CFF", "#6300A7FF", "#8707A6FF", "#A62098FF", "#C03A83FF", "#D5546EFF", "#F58C46FF"), name = "Strand Randomisation Index") +
  new_scale_colour() +
  geom_label(aes(label=round(percentID, digit = 1), color = percentID), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = -0.5) +
  scale_color_gradientn(colours = c("#440154FF", "#482173FF", "#433E85FF", "#38598CFF", "#2D708EFF", "#25858EFF", "#1E9B8AFF", "#2BB07FFF", "#51C56AFF", "#85D54AFF", "#C2DF23FF"), name = "Percent Identity")
nbl_fun



viewClade(nbl_fun, MRCA(nbl_fun, "Trichoderma_atroviride", "Trichoderma_pseudokoningii"))

viewClade(nbl_fun, MRCA(nbl_fun, "Pneumocystis_macacae", "Saccharomyces_cerevisiae"))

nbl_fun2 <- ggtree::collapse(nbl_fun, node=85)
nbl_fun2 <- ggtree::collapse(nbl_fun2, node=72)

trichoderma <- groupClade(nbl_fun, c(78,84,74))
viewClade(nbl_fun, MRCA(nbl_fun, "Trichoderma_atroviride", "Trichoderma_reesei"))


##With Branch Length
bl_fun <- ggtree(as.treedata(td2)) +
  ggtitle("Fungi: Percent Identity & Strand Randomisation Index") +
  geom_tippoint(aes(color=group), show.legend = FALSE) +
  scale_color_manual(values=c("#D81B60", "#1E88E5", "#FFC107", "#785EF0")) +
  new_scale_colour() +
  geom_tiplab(as_ylab=TRUE) +
  geom_label2(aes(label=round(strandRand, digit = 2), color = strandRand, subset = !is.na(as.numeric(strandRand)) & as.numeric(strandRand) < 1.01), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = 0.5) +
  scale_color_viridis(name = "Strand Randomisation Index") +
  new_scale_colour() +
  geom_label2(aes(label=round(percentID, digit = 1), color = percentID, subset = !is.na(as.numeric(percentID)) & as.numeric(percentID) != 55.0), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = -0.5) +
  scale_color_viridis(option="plasma", name = "Percent Identity")
bl_fun
```



##ggrepel Trees
```{r}
##ggrepel Tree
td2 <- groupClade(td, c(86,87,93,92,78,84,96,37,64,109,102,90,94,5,101,74,76,82,100,111,114,115))

repel_fun <- ggtree(as.treedata(td2)) +
  ggtitle("Fungi: Percent Identity & Strand Randomisation Index") +
  geom_tippoint(aes(color=group), show.legend = FALSE) +
  scale_color_manual(values=c("#f45151", "black", "#e55c3c", "black", "#d36629", "#d36629", "#c06e1a", "black", "black", "black", "black", "#b7931f", "#a79c28", "black", "#96a437", "#85ab48", "#73b15b", "#61b66f", "black", "black", "#4dba83", "#38bd97", "#21c0aa", "#0cc2bc")) +
  new_scale_colour() +
  geom_tiplab(as_ylab=TRUE) +
  geom_label_repel(min.segment.length = 0, aes(label=round(percentID, digit = 1), color = percentID), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = -0.5) +
  scale_color_gradientn(limits = c(40,100), colours = c("#440154FF", "#482173FF", "#433E85FF", "#38598CFF", "#2D708EFF", "#25858EFF", "#1E9B8AFF", "#2BB07FFF", "#51C56AFF", "#85D54AFF", "#C2DF23FF"), name = "Percent Identity") +
  new_scale_colour() +
  geom_label_repel(min.segment.length = 0, aes(label=round(strandRand, digit = 2), color = strandRand), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = 0.5) +
  scale_color_gradientn(limits = c(0,1), colours = c("#0D0887FF", "#3E049CFF", "#6300A7FF", "#8707A6FF", "#A62098FF", "#C03A83FF", "#D5546EFF", "#F58C46FF"), name = "Strand Randomisation Index")
repel_fun


##ggrepel Tree for Subsetting
repel_fun2 <- ggtree(as.treedata(repel_fun)) +
  ggtitle("Fungi: Percent Identity & Strand Randomisation Index") +
  geom_tippoint(aes(color=group), show.legend = FALSE, size = 3) +
  scale_color_manual(values=c("#f45151", "black", "#e55c3c", "black", "#d36629", "#d36629", "#c06e1a", "black", "black", "black", "black", "#b7931f", "#a79c28", "black", "#96a437", "#85ab48", "#73b15b", "#61b66f", "black", "black", "#4dba83", "#38bd97", "#21c0aa", "#0cc2bc")) +
  new_scale_colour() +
  geom_tiplab(as_ylab=TRUE, size = 15) +
  geom_label2(aes(label=round(percentID, digit = 1), color = percentID), label.size = 0.25, size = 4, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = -0.2) +
  scale_color_gradientn(limits = c(40,100), colours = c("#440154FF", "#482173FF", "#433E85FF", "#38598CFF", "#2D708EFF", "#25858EFF", "#1E9B8AFF", "#2BB07FFF", "#51C56AFF", "#85D54AFF", "#C2DF23FF"), name = "Percent Identity") +
  new_scale_colour() +
  geom_label2(aes(label=round(strandRand, digit = 2), color = strandRand, subset = !is.na(as.numeric(strandRand)) & as.numeric(strandRand) < 1.01), label.size = 0.25, size = 4, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = 0.2) +
  scale_color_gradientn(limits = c(0,1), colours = c("#0D0887FF", "#3E049CFF", "#6300A7FF", "#8707A6FF", "#A62098FF", "#C03A83FF", "#D5546EFF", "#F58C46FF"), name = "Strand Randomisation Index")

viewClade(repel_fun2, MRCA(repel_fun2, "Neurospora_crassa", "Aspergillus_niger_CBS_554.65"))

viewClade(repel_fun2, MRCA(repel_fun2, "Trichoderma_reesei", "Trichoderma_atroviride"))

viewClade(repel_fun2, MRCA(repel_fun2, "Trichoderma_virens_FT−333", "Aspergillus_niger_CBS_554.65"))

```


##Previously Studied Species
```{r}
##Selecting species that have been studied previously
clade_fun <- ggtree(as.treedata(td2), branch.length = "none") +
  ggtitle("Fungi: Species That Have Been Studied Previously") +
  geom_tippoint(aes(color=group), show.legend = FALSE) +
  scale_color_manual(values=c("black", "red3", "orange3", "yellow2", "green3", "blue3","purple3", "maroon3", "pink3")) +
  new_scale_colour() +
  geom_tiplab(as_ylab=TRUE) +
  geom_label(aes(label=round(strandRand, digit = 2), color = strandRand), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = 0.5) +
  scale_color_viridis(name = "Strand Randomisation Index") +
  new_scale_colour() +
  geom_label(aes(label=round(percentID, digit = 1), color = percentID), label.size = 0.25, size = 2, na.rm = TRUE, label.padding = unit(0.15, "lines"), nudge_y = -0.5) +
  scale_color_viridis(option="magma", name = "Percent Identity") +
  geom_hilight(node = c(30,31,12), fill = "green2", alpha = 0.3)
clade_fun

```

