---
title: "fungi-tree"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("brennern/ScrambledTreeBuilder")
library("ScrambledTreeBuilder")
library("GenomicBreaks") |> suppressPackageStartupMessages()
library("ggplot2")
library("pheatmap")
library("plotly")
library("dplyr")
library("dendextend")
library("BiocManager")
library("ggtree")
library("phytools")
library("ape")
library("rrapply")
library("tidytree")
library("viridis")
library("ggnewscale")
library("readr")
```


##Halobacteria Data
```{r}
params <- list()
params$resultsDir <- '/flash/LuscombeU/noa/fungi/results/genomicbreaks'
yamlFiles <- list.files(params$resultsDir, pattern = "*.yaml", full.names = TRUE)
names(yamlFiles) <- yamlFiles |> basename() |> sub(pat = ".yaml", rep="")

FungiDataFrame <- formatStats(yamlFiles)

valuesToBuildTheTree <- "percent_identity_global"
treeMatrix <- makeMatrix(FungiDataFrame, valuesToBuildTheTree, 100, 50)
valuesToPlaceOnLabels <- "index_avg_strandRand"
valueMatrix <- makeMatrix(FungiDataFrame, valuesToPlaceOnLabels, 1, 0.5)
```


##Halobacteria Percent Identity & Strand Randomisation Tree
```{r}
HClust <- hclust(dist(treeMatrix), method = "complete")
Tibble <- tidytree::as_tibble(tidytree::as.phylo(HClust))
tibbleWithValue <- makeValueTibble(Tibble, valueMatrix)
tibbleWithValue2 <- makeValueTibble(tibbleWithValue, treeMatrix)

Tree <- visualizeTree(tibbleWithValue, tibbleWithValue$value)
Tree + ggtitle(paste("Fungi tree built with", valuesToBuildTheTree, "and labelled with", valuesToPlaceOnLabels))
```
