---
title: "halobacteria-analysis"
output: html_document
---
##Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("brennern/ScrambledTreeBuilder")
library("ScrambledTreeBuilder")
library("GenomicBreaks") |> suppressPackageStartupMessages()
library("pheatmap")
library("plotly")
library("dplyr")
```


##Load Data
```{r}
params <- list()
params$resultsDir <- '/flash/LuscombeU/noa/halobacteria/results/genomicbreaks'
yamlFiles <- list.files(params$resultsDir, pattern = "*.yaml", full.names = TRUE)
names(yamlFiles) <- yamlFiles |> basename() |> sub(pat = ".yaml", rep="")
```


##Data Formatting
```{r}
HalobacteriaDataFrame <- formatStats(yamlFiles)

valuesToBuildTheTree <- "percent_identity_global"
treeMatrix <- makeMatrix(HalobacteriaDataFrame, valuesToBuildTheTree, 100, 50)
valuesToPlaceOnLabels <- "index_avg_strandRand"
valueMatrix <- makeMatrix(HalobacteriaDataFrame, valuesToPlaceOnLabels, 1, 0.5)
```


##Percent Identity and Mismatches
```{r}
HalobacteriaDataFrame$percent_identity_global <- HalobacteriaDataFrame$aligned_matches_bestpair_Total / HalobacteriaDataFrame$aligned_length_bestpair_Total * 100

HalobacteriaDataFrame$percent_mismatches_global <- HalobacteriaDataFrame$mismatching_aligned_bestpair_Total / HalobacteriaDataFrame$aligned_length_bestpair_Total * 100

ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_identity_global,  percent_mismatches_global)
```


##Percent Identity Global
```{r}
pheatmap::pheatmap(as.matrix(cluster::daisy(treeMatrix)), fontsize_row = 5, fontsize_col = 5)

pheatmap::pheatmap(as.matrix(treeMatrix), sym=T, fontsize_row = 5, fontsize_col = 5)
```


##Fraction of Genome Aligned
```{r}
HalobacteriaDataFrame$fraction_genome_aligned_target <- HalobacteriaDataFrame$aligned_width_target_bestpair_Total / HalobacteriaDataFrame$guessed_target_length_bestpair_Total * 100

HalobacteriaDataFrame$fraction_genome_aligned_query  <- HalobacteriaDataFrame$aligned_width_query_bestpair_Total  / HalobacteriaDataFrame$guessed_query_length_bestpair_Total  * 100

HalobacteriaDataFrame$fraction_genome_aligned_avg    <- (HalobacteriaDataFrame$fraction_genome_aligned_target + HalobacteriaDataFrame$fraction_genome_aligned_query) / 2

ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_mismatches_global, fraction_genome_aligned_avg, col = percent_identity_global)

ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_identity_global,   fraction_genome_aligned_avg, col = percent_mismatches_global)
```


##Fraction of Genome Chained
```{r}
HalobacteriaDataFrame$fraction_genome_chained_target <- HalobacteriaDataFrame$chain_width_target_bestpair_Total / HalobacteriaDataFrame$guessed_target_length_bestpair_Total * 100
HalobacteriaDataFrame$fraction_genome_chained_query  <- HalobacteriaDataFrame$chain_width_query_bestpair_Total / HalobacteriaDataFrame$guessed_query_length_bestpair_Total  * 100
HalobacteriaDataFrame$fraction_genome_chained_avg    <- (HalobacteriaDataFrame$fraction_genome_chained_target + HalobacteriaDataFrame$fraction_genome_chained_query) / 2

ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_mismatches_global, fraction_genome_chained_avg, col = percent_identity_global)
```


##Width of Aligned Regions
```{r}
##Aligned Width 1
ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_identity_global, aligned_length_Mean, col = percent_mismatches_global)
ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_mismatches_global, aligned_length_Mean, col = percent_identity_global)

##Aligned Width 2
ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_identity_global, aligned_width_target_bestpair_Mean / guessed_target_length_bestpair_Total, col = percent_mismatches_global) + scale_y_log10()

ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_identity_global, aligned_width_query_bestpair_Mean  / guessed_query_length_bestpair_Total, col = percent_mismatches_global) + scale_y_log10()

ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_identity_global, aligned_length_bestpair_Mean  / (guessed_target_length_bestpair_Total + guessed_query_length_bestpair_Total) / 2, col = percent_mismatches_global)  + scale_y_log10()
```


##Length of the Chains
```{r}
ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_identity_global, chain_width_target_bestpair_Mean, col = percent_mismatches_global) + scale_y_log10()

ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_mismatches_global, chain_width_target_bestpair_Mean, col = percent_identity_global) + scale_y_log10()

ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_identity_global, chain_width_target_bestpair_Mean / guessed_target_length_bestpair_Mean, col = percent_mismatches_global) + scale_y_log10()

ggplot(HalobacteriaDataFrame) + geom_point() + aes(percent_identity_global, chain_width_query_bestpair_Mean  / guessed_query_length_bestpair_Mean, col = percent_mismatches_global) + scale_y_log10()
```


##Indices
```{r}
HalobacteriaDataFrame$index_avg_synteny <- (HalobacteriaDataFrame$index_synteny_target_bestpair + HalobacteriaDataFrame$index_synteny_query_bestpair ) / 2

HalobacteriaDataFrame$index_avg_correlation <- (HalobacteriaDataFrame$index_correlation_target_bestpair + HalobacteriaDataFrame$index_correlation_query_bestpair ) / 2

HalobacteriaDataFrame$index_avg_GOCvicinity4 <- (HalobacteriaDataFrame$index_GOCvicinity4_target_bestpair + HalobacteriaDataFrame$index_GOCvicinity4_query_bestpair ) / 2

HalobacteriaDataFrame$index_avg_strandRand <- (HalobacteriaDataFrame$index_strandRand_target_bestpair + HalobacteriaDataFrame$index_strandRand_query_bestpair ) / 2

HalobacteriaDataFrame[,grepl("index_avg", colnames(HalobacteriaDataFrame))] |> pairs()
```


##Percent Identity Vs. Strand Randomisation Index Graph
```{r}
HalobacteriaDataFrame$lab <- ifelse(HalobacteriaDataFrame$species1 > HalobacteriaDataFrame$species2,
       paste(HalobacteriaDataFrame$species1, HalobacteriaDataFrame$species2, sep = "\n"),
       paste(HalobacteriaDataFrame$species2, HalobacteriaDataFrame$species1, sep = "\n"))

HalobacteriaDataFrame |>
  #dplyr::filter(index_avg_synteny > 0.25) |>
  dplyr::group_by(lab) |>
  dplyr::summarise(percent_identity_global = mean(percent_identity_global),
                   index_avg_strandRand = mean(index_avg_strandRand),
                   lab = lab) |>
  ggplot() +
    geom_point() +
    aes(percent_identity_global, index_avg_strandRand, label=lab) +
    scale_x_continuous("Percent Identity") +
    scale_y_continuous("Strand Randomisation Index") +
    theme_bw() +
    ggtitle("Halobacteria: Percent Identity Vs. Strand Randomisation Index") +
    geom_text() -> gg
    plotly::ggplotly(gg)
```


##Similarity Vs. Synteny Index
```{r}
ggplot(HalobacteriaDataFrame) + theme_bw() +
  aes(percent_identity_global, index_avg_synteny, col = percent_mismatches_global) +
  xlab("Identity between aligned regions (%)") +
  ylab("Synteny index") +
  geom_point()
```


##Similarity Vs. Correlation Index
```{r}
ggplot(HalobacteriaDataFrame) + theme_bw() +
  aes(percent_identity_global, index_avg_strandRand, col = percent_mismatches_global) +
  xlab("Identity between aligned regions (%)") +
  ylab("Strand randomisation index") +
  geom_point() + geom_smooth()
```


##Gene Order Correlation
```{r}
ggplot(HalobacteriaDataFrame) +
  aes(percent_identity_global, index_avg_GOCvicinity4) +
  aes(color = species1) +
  xlab("Similarity between aligned regions") +
  ylab("abs(correlation index)") +
  geom_point()
```


